activate your account:
https://leetcode.com/accounts/confirm-email/p494fcvrj8syyteyqggppxeodrpd
oul0arf2sstypgjiegot8atkuvbchny6kmte/
<https://u2842676.ct.sendgrid.net/wf/click?upn=lGt2Ysw-2FSYCrI4rbXya1AT4
cjcnKiW-2F-2FBKLzDdootYxgGLsggncLn86fBOA89ivav0ndbRkJ2HlxbzHcMYP3mf86MY2
3nam8rTTsgA8EuUxLpl4b2KqTjXC0qRmEpD8JDFiaUZKqhUPosqGuLsmZO3DauHCjlT-2BGX
ZR1XmZMWJM-3D_GJ4jOqo7ORrvAH8ETEUi-2BSeQ9aonM8fAZa4lJbfbnqTHSx8MwlbMk8-2
F2JJ5uNbNfimxClcrc8ke5mEtggp1BPP3hhB5jxFAXXm1PEVRsTaBhCtFfZ6JttxDabsLNeP
aEgEzt4czqTNpaFfR8FAAgoZI47xvCr2deZp3po8rg0-2FTRlh0lC-2FYUijk0RKNhfxlUmP
4KjnNF4Zb03Dqs2IoC4Q-3D-3D> 

Have fun coding, and don't hesitate to contact us with your feedback.


<https://u2842676.ct.sendgrid.net/wf/open?upn=GJ4jOqo7ORrvAH8ETEUi-2BSeQ
9aonM8fAZa4lJbfbnqTHSx8MwlbMk8-2F2JJ5uNbNfV3wfH0ixSb6ALmYafAj01H17dDOKSM
dZT2alY0cGLxSUGaCs1s9JZwjtfrg7dBMXCwpxcrHZxxidTJshKa1QP-2FuQTGBh-2FLq86i
UM2uzqe-2Fi-2F9Oisn9HkeW70g6qLa-2F-2FiPgY9b4pU9QHljq2E2VUsow-3D-3D> 
	by mx19 (Coremail) with SMTP id x8mowACny6Xy3VtX3myeAg--.434S3;
	Sat, 11 Jun 2016 17:46:59 +0800 (CST)
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=sendgrid.net; 
	h=mime-version:subject:from:to:content-type; s=smtpapi; 
	bh=FHUfm5dYGrv60Q+9veRaDskwRPg=; b=gqRaUze5AlTGdXN7tLnwVvPjud5Pa
	p0htP6PuMFWa5OVYMqxHSlrwjF7KjryU4FrqRUld1oqkTOiyrialMEyJtne5H5+g
	moJcgs+fVIm1fvLul6eADWCI74tdBuwgDKZVRTo6zxi4SX1XXmO1waBSL+39+VEP
	z/3TyXFfZfHPFU=
Received: by filter0068p1las1.sendgrid.net with SMTP id filter0068p1las1.20768.575BDDF21
        2016-06-11 09:46:26.086682117 +0000 UTC
Received: from noj-rc-bf9yj (li85-212.members.linode.com [74.207.243.212])
	by ismtpd0004p1las1.sendgrid.net (SG) with ESMTP id 6LM0spUNRi2wyN6Us4rRIQ
	for <sam_msn@126.com>; Sat, 11 Jun 2016 09:46:25.868 +0000 (UTC)
MIME-Version: 1.0
Subject: [LeetCode OJ] Confirm E-mail Address
From: LeetCode OJ <oj@leetcode.com>
To: sam_msn@126.com
Date: Sat, 11 Jun 2016 09:46:25 -0000
Message-ID: <20160611094625.4090.24148@noj-rc-bf9yj>
Content-type: multipart/alternative; boundary="----------=_1465638386-20908-822"
X-SG-EID: cc/ALO3n8o2y0BoUY1Nwt7cRae1k2xOaSgOunZF6zy8glCFhzHeDS6kcQVvba5HX0i1gbzOSCqRa5p
 CyXgYrGCD9TlfuXnxXL1OAlEdX23QZmxf+756unfFKFtyxx+8uGATx04XmtD0OhONzlrG6OBVTi68s
 v2oonnvpiQas653VATQV1BSxgI4WEnW4HBjrhn8hKrr20ViLEe7Fno9EFA==
X-CM-TRANSID:x8mowACny6Xy3VtX3myeAg--.434S3
Authentication-Results: mx19; spf=permerror smtp.mail=bounces+2842676-
	df2e-sam_msn=126.com@sendgrid.net; dkim=pass header.i=@sendgrid.net
X-Coremail-Antispam: 1Uf129KBjDUn29KB7ZKAUJUUUUU529EdanIXcx71UUUUU7v73
	VFW2AGmfu7bjvjm3AaLaJ3UbIYCTnIWIevJa73UjIFyTuYvjxUxiiSDUUUU
Sender: bounces+2842676-df2e-sam_msn=126.com@sendgrid.net


From:\s+([a-zA-Z0-9_\- ]+)<[\w\-_]+@[\w]+\.[a-zA-Z]+>